<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->upsert([
            ['id' => 57, 'name' => 'Colombia'],
        ], ['id']);

        $departments = [
            ['id' => 5, 'name' => 'ANTIOQUIA'],
            ['id' => 8, 'name' => 'ATLÁNTICO'],
            ['id' => 11, 'name' => 'BOGOTÁ, D.C.'],
            ['id' => 13, 'name' => 'BOLÍVAR'],
            ['id' => 15, 'name' => 'BOYACÁ'],
            ['id' => 17, 'name' => 'CALDAS'],
            ['id' => 18, 'name' => 'CAQUETÁ'],
            ['id' => 19, 'name' => 'CAUCA'],
            ['id' => 20, 'name' => 'CESAR'],
            ['id' => 23, 'name' => 'CÓRDOBA'],
            ['id' => 25, 'name' => 'CUNDINAMARCA'],
            ['id' => 27, 'name' => 'CHOCÓ'],
            ['id' => 41, 'name' => 'HUILA'],
            ['id' => 44, 'name' => 'LA GUAJIRA'],
            ['id' => 47, 'name' => 'MAGDALENA'],
            ['id' => 50, 'name' => 'META'],
            ['id' => 52, 'name' => 'NARIÑO'],
            ['id' => 54, 'name' => 'NORTE DE SANTANDER'],
            ['id' => 63, 'name' => 'QUINDÍO'],
            ['id' => 66, 'name' => 'RISARALDA'],
            ['id' => 68, 'name' => 'SANTANDER'],
            ['id' => 70, 'name' => 'SUCRE'],
            ['id' => 73, 'name' => 'TOLIMA'],
            ['id' => 76, 'name' => 'VALLE DEL CAUCA'],
            ['id' => 81, 'name' => 'ARAUCA'],
            ['id' => 85, 'name' => 'CASANARE'],
            ['id' => 86, 'name' => 'PUTUMAYO'],
            ['id' => 88, 'name' => 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA'],
            ['id' => 91, 'name' => 'AMAZONAS'],
            ['id' => 94, 'name' => 'GUAINÍA'],
            ['id' => 95, 'name' => 'GUAVIARE'],
            ['id' => 97, 'name' => 'VAUPÉS'],
            ['id' => 99, 'name' => 'VICHADA'],
        ];

        $cities = [
            ['id' => 1, 'name' => 'Abriaquí', 'state_id' => 5],
            ['id' => 2, 'name' => 'Acacías', 'state_id' => 50],
            ['id' => 3, 'name' => 'Acandí', 'state_id' => 27],
            ['id' => 4, 'name' => 'Acevedo', 'state_id' => 41],
            ['id' => 5, 'name' => 'Achí', 'state_id' => 13],
            ['id' => 6, 'name' => 'Agrado', 'state_id' => 41],
            ['id' => 7, 'name' => 'Agua de Dios', 'state_id' => 25],
            ['id' => 8, 'name' => 'Aguachica', 'state_id' => 20],
            ['id' => 9, 'name' => 'Aguada', 'state_id' => 68],
            ['id' => 10, 'name' => 'Aguadas', 'state_id' => 17],
            ['id' => 11, 'name' => 'Aguazul', 'state_id' => 85],
            ['id' => 12, 'name' => 'Agustín Codazzi', 'state_id' => 20],
            ['id' => 13, 'name' => 'Aipe', 'state_id' => 41],
            ['id' => 14, 'name' => 'Albania', 'state_id' => 18],
            ['id' => 15, 'name' => 'Albania', 'state_id' => 44],
            ['id' => 16, 'name' => 'Albania', 'state_id' => 68],
            ['id' => 17, 'name' => 'Albán', 'state_id' => 25],
            ['id' => 18, 'name' => 'Albán (San José)', 'state_id' => 52],
            ['id' => 19, 'name' => 'Alcalá', 'state_id' => 76],
            ['id' => 20, 'name' => 'Alejandria', 'state_id' => 5],
            ['id' => 21, 'name' => 'Algarrobo', 'state_id' => 47],
            ['id' => 22, 'name' => 'Algeciras', 'state_id' => 41],
            ['id' => 23, 'name' => 'Almaguer', 'state_id' => 19],
            ['id' => 24, 'name' => 'Almeida', 'state_id' => 15],
            ['id' => 25, 'name' => 'Alpujarra', 'state_id' => 73],
            ['id' => 26, 'name' => 'Altamira', 'state_id' => 41],
            ['id' => 27, 'name' => 'Alto Baudó (Pie de Pato)', 'state_id' => 27],
            ['id' => 28, 'name' => 'Altos del Rosario', 'state_id' => 13],
            ['id' => 29, 'name' => 'Alvarado', 'state_id' => 73],
            ['id' => 30, 'name' => 'Amagá', 'state_id' => 5],
            ['id' => 31, 'name' => 'Amalfi', 'state_id' => 5],
            ['id' => 32, 'name' => 'Ambalema', 'state_id' => 73],
            ['id' => 33, 'name' => 'Anapoima', 'state_id' => 25],
            ['id' => 34, 'name' => 'Ancuya', 'state_id' => 52],
            ['id' => 35, 'name' => 'Andalucía', 'state_id' => 76],
            ['id' => 36, 'name' => 'Andes', 'state_id' => 5],
            ['id' => 37, 'name' => 'Angelópolis', 'state_id' => 5],
            ['id' => 38, 'name' => 'Angostura', 'state_id' => 5],
            ['id' => 39, 'name' => 'Anolaima', 'state_id' => 25],
            ['id' => 40, 'name' => 'Anorí', 'state_id' => 5],
            ['id' => 41, 'name' => 'Anserma', 'state_id' => 17],
            ['id' => 42, 'name' => 'Ansermanuevo', 'state_id' => 76],
            ['id' => 43, 'name' => 'Anzoátegui', 'state_id' => 73],
            ['id' => 44, 'name' => 'Anzá', 'state_id' => 5],
            ['id' => 45, 'name' => 'Apartadó', 'state_id' => 5],
            ['id' => 46, 'name' => 'Apulo', 'state_id' => 25],
            ['id' => 47, 'name' => 'Apía', 'state_id' => 66],
            ['id' => 48, 'name' => 'Aquitania', 'state_id' => 15],
            ['id' => 49, 'name' => 'Aracataca', 'state_id' => 47],
            ['id' => 50, 'name' => 'Aranzazu', 'state_id' => 17],
            ['id' => 51, 'name' => 'Aratoca', 'state_id' => 68],
            ['id' => 52, 'name' => 'Arauca', 'state_id' => 81],
            ['id' => 53, 'name' => 'Arauquita', 'state_id' => 81],
            ['id' => 54, 'name' => 'Arbeláez', 'state_id' => 25],
            ['id' => 55, 'name' => 'Arboleda (Berruecos)', 'state_id' => 52],
            ['id' => 56, 'name' => 'Arboledas', 'state_id' => 54],
            ['id' => 57, 'name' => 'Arboletes', 'state_id' => 5],
            ['id' => 58, 'name' => 'Arcabuco', 'state_id' => 15],
            ['id' => 59, 'name' => 'Arenal', 'state_id' => 13],
            ['id' => 60, 'name' => 'Argelia', 'state_id' => 5],
            ['id' => 61, 'name' => 'Argelia', 'state_id' => 19],
            ['id' => 62, 'name' => 'Argelia', 'state_id' => 76],
            ['id' => 63, 'name' => 'Ariguaní (El Difícil)', 'state_id' => 47],
            ['id' => 64, 'name' => 'Arjona', 'state_id' => 13],
            ['id' => 65, 'name' => 'Armenia', 'state_id' => 5],
            ['id' => 66, 'name' => 'Armenia', 'state_id' => 63],
            ['id' => 67, 'name' => 'Armero (Guayabal)', 'state_id' => 73],
            ['id' => 68, 'name' => 'Arroyohondo', 'state_id' => 13],
            ['id' => 69, 'name' => 'Astrea', 'state_id' => 20],
            ['id' => 70, 'name' => 'Ataco', 'state_id' => 73],
            ['id' => 71, 'name' => 'Atrato (Yuto)', 'state_id' => 27],
            ['id' => 72, 'name' => 'Ayapel', 'state_id' => 23],
            ['id' => 73, 'name' => 'Bagadó', 'state_id' => 27],
            ['id' => 74, 'name' => 'Bahía Solano (Mútis)', 'state_id' => 27],
            ['id' => 75, 'name' => 'Bajo Baudó (Pizarro)', 'state_id' => 27],
            ['id' => 76, 'name' => 'Balboa', 'state_id' => 19],
            ['id' => 77, 'name' => 'Balboa', 'state_id' => 66],
            ['id' => 78, 'name' => 'Baranoa', 'state_id' => 8],
            ['id' => 79, 'name' => 'Baraya', 'state_id' => 41],
            ['id' => 80, 'name' => 'Barbacoas', 'state_id' => 52],
            ['id' => 81, 'name' => 'Barbosa', 'state_id' => 5],
            ['id' => 82, 'name' => 'Barbosa', 'state_id' => 68],
            ['id' => 83, 'name' => 'Barichara', 'state_id' => 68],
            ['id' => 84, 'name' => 'Barranca de Upía', 'state_id' => 50],
            ['id' => 85, 'name' => 'Barrancabermeja', 'state_id' => 68],
            ['id' => 86, 'name' => 'Barrancas', 'state_id' => 44],
            ['id' => 87, 'name' => 'Barranco de Loba', 'state_id' => 13],
            ['id' => 88, 'name' => 'Barranquilla', 'state_id' => 8],
            ['id' => 89, 'name' => 'Becerríl', 'state_id' => 20],
            ['id' => 90, 'name' => 'Belalcázar', 'state_id' => 17],
            ['id' => 91, 'name' => 'Bello', 'state_id' => 5],
            ['id' => 92, 'name' => 'Belmira', 'state_id' => 5],
            ['id' => 93, 'name' => 'Beltrán', 'state_id' => 25],
            ['id' => 94, 'name' => 'Belén', 'state_id' => 15],
            ['id' => 95, 'name' => 'Belén', 'state_id' => 52],
            ['id' => 96, 'name' => 'Belén de Bajirá', 'state_id' => 27],
            ['id' => 97, 'name' => 'Belén de Umbría', 'state_id' => 66],
            ['id' => 98, 'name' => 'Belén de los Andaquíes', 'state_id' => 18],
            ['id' => 99, 'name' => 'Berbeo', 'state_id' => 15],
            ['id' => 100, 'name' => 'Betania', 'state_id' => 5],
            ['id' => 101, 'name' => 'Beteitiva', 'state_id' => 15],
            ['id' => 102, 'name' => 'Betulia', 'state_id' => 5],
            ['id' => 103, 'name' => 'Betulia', 'state_id' => 68],
            ['id' => 104, 'name' => 'Bituima', 'state_id' => 25],
            ['id' => 105, 'name' => 'Boavita', 'state_id' => 15],
            ['id' => 106, 'name' => 'Bochalema', 'state_id' => 54],
            ['id' => 107, 'name' => 'Bogotá D.C.', 'state_id' => 11],
            ['id' => 108, 'name' => 'Bojacá', 'state_id' => 25],
            ['id' => 109, 'name' => 'Bojayá (Bellavista)', 'state_id' => 27],
            ['id' => 110, 'name' => 'Bolívar', 'state_id' => 5],
            ['id' => 111, 'name' => 'Bolívar', 'state_id' => 19],
            ['id' => 112, 'name' => 'Bolívar', 'state_id' => 68],
            ['id' => 113, 'name' => 'Bolívar', 'state_id' => 76],
            ['id' => 114, 'name' => 'Bosconia', 'state_id' => 20],
            ['id' => 115, 'name' => 'Boyacá', 'state_id' => 15],
            ['id' => 116, 'name' => 'Briceño', 'state_id' => 5],
            ['id' => 117, 'name' => 'Briceño', 'state_id' => 15],
            ['id' => 118, 'name' => 'Bucaramanga', 'state_id' => 68],
            ['id' => 119, 'name' => 'Bucarasica', 'state_id' => 54],
            ['id' => 120, 'name' => 'Buenaventura', 'state_id' => 76],
            ['id' => 121, 'name' => 'Buenavista', 'state_id' => 15],
            ['id' => 122, 'name' => 'Buenavista', 'state_id' => 23],
            ['id' => 123, 'name' => 'Buenavista', 'state_id' => 63],
            ['id' => 124, 'name' => 'Buenavista', 'state_id' => 70],
            ['id' => 125, 'name' => 'Buenos Aires', 'state_id' => 19],
            ['id' => 126, 'name' => 'Buesaco', 'state_id' => 52],
            ['id' => 127, 'name' => 'Buga', 'state_id' => 76],
            ['id' => 128, 'name' => 'Bugalagrande', 'state_id' => 76],
            ['id' => 129, 'name' => 'Burítica', 'state_id' => 5],
            ['id' => 130, 'name' => 'Busbanza', 'state_id' => 15],
            ['id' => 131, 'name' => 'Cabrera', 'state_id' => 25],
            ['id' => 132, 'name' => 'Cabrera', 'state_id' => 68],
            ['id' => 133, 'name' => 'Cabuyaro', 'state_id' => 50],
            ['id' => 134, 'name' => 'Cachipay', 'state_id' => 25],
            ['id' => 135, 'name' => 'Caicedo', 'state_id' => 5],
            ['id' => 136, 'name' => 'Caicedonia', 'state_id' => 76],
            ['id' => 137, 'name' => 'Caimito', 'state_id' => 70],
            ['id' => 138, 'name' => 'Cajamarca', 'state_id' => 73],
            ['id' => 139, 'name' => 'Cajibío', 'state_id' => 19],
            ['id' => 140, 'name' => 'Cajicá', 'state_id' => 25],
            ['id' => 141, 'name' => 'Calamar', 'state_id' => 13],
            ['id' => 142, 'name' => 'Calamar', 'state_id' => 95],
            ['id' => 143, 'name' => 'Calarcá', 'state_id' => 63],
            ['id' => 144, 'name' => 'Caldas', 'state_id' => 5],
            ['id' => 145, 'name' => 'Caldas', 'state_id' => 15],
            ['id' => 146, 'name' => 'Caldono', 'state_id' => 19],
            ['id' => 147, 'name' => 'California', 'state_id' => 68],
            ['id' => 148, 'name' => 'Calima (Darién)', 'state_id' => 76],
            ['id' => 149, 'name' => 'Caloto', 'state_id' => 19],
            ['id' => 150, 'name' => 'Calí', 'state_id' => 76],
            ['id' => 151, 'name' => 'Campamento', 'state_id' => 5],
            ['id' => 152, 'name' => 'Campo de la Cruz', 'state_id' => 8],
            ['id' => 153, 'name' => 'Campoalegre', 'state_id' => 41],
            ['id' => 154, 'name' => 'Campohermoso', 'state_id' => 15],
            ['id' => 155, 'name' => 'Canalete', 'state_id' => 23],
            ['id' => 156, 'name' => 'Candelaria', 'state_id' => 8],
            ['id' => 157, 'name' => 'Candelaria', 'state_id' => 76],
            ['id' => 158, 'name' => 'Cantagallo', 'state_id' => 13],
            ['id' => 159, 'name' => 'Cantón de San Pablo', 'state_id' => 27],
            ['id' => 160, 'name' => 'Caparrapí', 'state_id' => 25],
            ['id' => 161, 'name' => 'Capitanejo', 'state_id' => 68],
            ['id' => 162, 'name' => 'Caracolí', 'state_id' => 5],
            ['id' => 163, 'name' => 'Caramanta', 'state_id' => 5],
            ['id' => 164, 'name' => 'Carcasí', 'state_id' => 68],
            ['id' => 165, 'name' => 'Carepa', 'state_id' => 5],
            ['id' => 166, 'name' => 'Carmen de Apicalá', 'state_id' => 73],
            ['id' => 167, 'name' => 'Carmen de Carupa', 'state_id' => 25],
            ['id' => 168, 'name' => 'Carmen de Viboral', 'state_id' => 5],
            ['id' => 169, 'name' => 'Carmen del Darién (CURBARADÓ)', 'state_id' => 27],
            ['id' => 170, 'name' => 'Carolina', 'state_id' => 5],
            ['id' => 171, 'name' => 'Cartagena', 'state_id' => 13],
            ['id' => 172, 'name' => 'Cartagena del Chairá', 'state_id' => 18],
            ['id' => 173, 'name' => 'Cartago', 'state_id' => 76],
            ['id' => 174, 'name' => 'Carurú', 'state_id' => 97],
            ['id' => 175, 'name' => 'Casabianca', 'state_id' => 73],
            ['id' => 176, 'name' => 'Castilla la Nueva', 'state_id' => 50],
            ['id' => 177, 'name' => 'Caucasia', 'state_id' => 5],
            ['id' => 178, 'name' => 'Cañasgordas', 'state_id' => 5],
            ['id' => 179, 'name' => 'Cepita', 'state_id' => 68],
            ['id' => 180, 'name' => 'Cereté', 'state_id' => 23],
            ['id' => 181, 'name' => 'Cerinza', 'state_id' => 15],
            ['id' => 182, 'name' => 'Cerrito', 'state_id' => 68],
            ['id' => 183, 'name' => 'Cerro San Antonio', 'state_id' => 47],
            ['id' => 184, 'name' => 'Chachaguí', 'state_id' => 52],
            ['id' => 185, 'name' => 'Chaguaní', 'state_id' => 25],
            ['id' => 186, 'name' => 'Chalán', 'state_id' => 70],
            ['id' => 187, 'name' => 'Chaparral', 'state_id' => 73],
            ['id' => 188, 'name' => 'Charalá', 'state_id' => 68],
            ['id' => 189, 'name' => 'Charta', 'state_id' => 68],
            ['id' => 190, 'name' => 'Chigorodó', 'state_id' => 5],
            ['id' => 191, 'name' => 'Chima', 'state_id' => 68],
            ['id' => 192, 'name' => 'Chimichagua', 'state_id' => 20],
            ['id' => 193, 'name' => 'Chimá', 'state_id' => 23],
            ['id' => 194, 'name' => 'Chinavita', 'state_id' => 15],
            ['id' => 195, 'name' => 'Chinchiná', 'state_id' => 17],
            ['id' => 196, 'name' => 'Chinácota', 'state_id' => 54],
            ['id' => 197, 'name' => 'Chinú', 'state_id' => 23],
            ['id' => 198, 'name' => 'Chipaque', 'state_id' => 25],
            ['id' => 199, 'name' => 'Chipatá', 'state_id' => 68],
            ['id' => 200, 'name' => 'Chiquinquirá', 'state_id' => 15],
            ['id' => 201, 'name' => 'Chiriguaná', 'state_id' => 20],
            ['id' => 202, 'name' => 'Chiscas', 'state_id' => 15],
            ['id' => 203, 'name' => 'Chita', 'state_id' => 15],
            ['id' => 204, 'name' => 'Chitagá', 'state_id' => 54],
            ['id' => 205, 'name' => 'Chitaraque', 'state_id' => 15],
            ['id' => 206, 'name' => 'Chivatá', 'state_id' => 15],
            ['id' => 207, 'name' => 'Chivolo', 'state_id' => 47],
            ['id' => 208, 'name' => 'Choachí', 'state_id' => 25],
            ['id' => 209, 'name' => 'Chocontá', 'state_id' => 25],
            ['id' => 210, 'name' => 'Chámeza', 'state_id' => 85],
            ['id' => 211, 'name' => 'Chía', 'state_id' => 25],
            ['id' => 212, 'name' => 'Chíquiza', 'state_id' => 15],
            ['id' => 213, 'name' => 'Chívor', 'state_id' => 15],
            ['id' => 214, 'name' => 'Cicuco', 'state_id' => 13],
            ['id' => 215, 'name' => 'Cimitarra', 'state_id' => 68],
            ['id' => 216, 'name' => 'Circasia', 'state_id' => 63],
            ['id' => 217, 'name' => 'Cisneros', 'state_id' => 5],
            ['id' => 218, 'name' => 'Ciénaga', 'state_id' => 15],
            ['id' => 219, 'name' => 'Ciénaga', 'state_id' => 47],
            ['id' => 220, 'name' => 'Ciénaga de Oro', 'state_id' => 23],
            ['id' => 221, 'name' => 'Clemencia', 'state_id' => 13],
            ['id' => 222, 'name' => 'Cocorná', 'state_id' => 5],
            ['id' => 223, 'name' => 'Coello', 'state_id' => 73],
            ['id' => 224, 'name' => 'Cogua', 'state_id' => 25],
            ['id' => 225, 'name' => 'Colombia', 'state_id' => 41],
            ['id' => 226, 'name' => 'Colosó (Ricaurte)', 'state_id' => 70],
            ['id' => 227, 'name' => 'Colón', 'state_id' => 86],
            ['id' => 228, 'name' => 'Colón (Génova)', 'state_id' => 52],
            ['id' => 229, 'name' => 'Concepción', 'state_id' => 5],
            ['id' => 230, 'name' => 'Concepción', 'state_id' => 68],
            ['id' => 231, 'name' => 'Concordia', 'state_id' => 5],
            ['id' => 232, 'name' => 'Concordia', 'state_id' => 47],
            ['id' => 233, 'name' => 'Condoto', 'state_id' => 27],
            ['id' => 234, 'name' => 'Confines', 'state_id' => 68],
            ['id' => 235, 'name' => 'Consaca', 'state_id' => 52],
            ['id' => 236, 'name' => 'Contadero', 'state_id' => 52],
            ['id' => 237, 'name' => 'Contratación', 'state_id' => 68],
            ['id' => 238, 'name' => 'Convención', 'state_id' => 54],
            ['id' => 239, 'name' => 'Copacabana', 'state_id' => 5],
            ['id' => 240, 'name' => 'Coper', 'state_id' => 15],
            ['id' => 241, 'name' => 'Cordobá', 'state_id' => 63],
            ['id' => 242, 'name' => 'Corinto', 'state_id' => 19],
            ['id' => 243, 'name' => 'Coromoro', 'state_id' => 68],
            ['id' => 244, 'name' => 'Corozal', 'state_id' => 70],
            ['id' => 245, 'name' => 'Corrales', 'state_id' => 15],
            ['id' => 246, 'name' => 'Cota', 'state_id' => 25],
            ['id' => 247, 'name' => 'Cotorra', 'state_id' => 23],
            ['id' => 248, 'name' => 'Covarachía', 'state_id' => 15],
            ['id' => 249, 'name' => 'Coveñas', 'state_id' => 70],
            ['id' => 250, 'name' => 'Coyaima', 'state_id' => 73],
            ['id' => 251, 'name' => 'Cravo Norte', 'state_id' => 81],
            ['id' => 252, 'name' => 'Cuaspud (Carlosama)', 'state_id' => 52],
            ['id' => 253, 'name' => 'Cubarral', 'state_id' => 50],
            ['id' => 254, 'name' => 'Cubará', 'state_id' => 15],
            ['id' => 255, 'name' => 'Cucaita', 'state_id' => 15],
            ['id' => 256, 'name' => 'Cucunubá', 'state_id' => 25],
            ['id' => 257, 'name' => 'Cucutilla', 'state_id' => 54],
            ['id' => 258, 'name' => 'Cuitiva', 'state_id' => 15],
            ['id' => 259, 'name' => 'Cumaral', 'state_id' => 50],
            ['id' => 260, 'name' => 'Cumaribo', 'state_id' => 99],
            ['id' => 261, 'name' => 'Cumbal', 'state_id' => 52],
            ['id' => 262, 'name' => 'Cumbitara', 'state_id' => 52],
            ['id' => 263, 'name' => 'Cunday', 'state_id' => 73],
            ['id' => 264, 'name' => 'Curillo', 'state_id' => 18],
            ['id' => 265, 'name' => 'Curití', 'state_id' => 68],
            ['id' => 266, 'name' => 'Curumaní', 'state_id' => 20],
            ['id' => 267, 'name' => 'Cáceres', 'state_id' => 5],
            ['id' => 268, 'name' => 'Cáchira', 'state_id' => 54],
            ['id' => 269, 'name' => 'Cácota', 'state_id' => 54],
            ['id' => 270, 'name' => 'Cáqueza', 'state_id' => 25],
            ['id' => 271, 'name' => 'Cértegui', 'state_id' => 27],
            ['id' => 272, 'name' => 'Cómbita', 'state_id' => 15],
            ['id' => 273, 'name' => 'Córdoba', 'state_id' => 13],
            ['id' => 274, 'name' => 'Córdoba', 'state_id' => 52],
            ['id' => 275, 'name' => 'Cúcuta', 'state_id' => 54],
            ['id' => 276, 'name' => 'Dabeiba', 'state_id' => 5],
            ['id' => 277, 'name' => 'Dagua', 'state_id' => 76],
            ['id' => 278, 'name' => 'Dibulla', 'state_id' => 44],
            ['id' => 279, 'name' => 'Distracción', 'state_id' => 44],
            ['id' => 280, 'name' => 'Dolores', 'state_id' => 73],
            ['id' => 281, 'name' => 'Don Matías', 'state_id' => 5],
            ['id' => 282, 'name' => 'Dos Quebradas', 'state_id' => 66],
            ['id' => 283, 'name' => 'Duitama', 'state_id' => 15],
            ['id' => 284, 'name' => 'Durania', 'state_id' => 54],
            ['id' => 285, 'name' => 'Ebéjico', 'state_id' => 5],
            ['id' => 286, 'name' => 'El Bagre', 'state_id' => 5],
            ['id' => 287, 'name' => 'El Banco', 'state_id' => 47],
            ['id' => 288, 'name' => 'El Cairo', 'state_id' => 76],
            ['id' => 289, 'name' => 'El Calvario', 'state_id' => 50],
            ['id' => 290, 'name' => 'El Carmen', 'state_id' => 54],
            ['id' => 291, 'name' => 'El Carmen', 'state_id' => 68],
            ['id' => 292, 'name' => 'El Carmen de Atrato', 'state_id' => 27],
            ['id' => 293, 'name' => 'El Carmen de Bolívar', 'state_id' => 13],
            ['id' => 294, 'name' => 'El Castillo', 'state_id' => 50],
            ['id' => 295, 'name' => 'El Cerrito', 'state_id' => 76],
            ['id' => 296, 'name' => 'El Charco', 'state_id' => 52],
            ['id' => 297, 'name' => 'El Cocuy', 'state_id' => 15],
            ['id' => 298, 'name' => 'El Colegio', 'state_id' => 25],
            ['id' => 299, 'name' => 'El Copey', 'state_id' => 20],
            ['id' => 300, 'name' => 'El Doncello', 'state_id' => 18],
            ['id' => 301, 'name' => 'El Dorado', 'state_id' => 50],
            ['id' => 302, 'name' => 'El Dovio', 'state_id' => 76],
            ['id' => 303, 'name' => 'El Espino', 'state_id' => 15],
            ['id' => 304, 'name' => 'El Guacamayo', 'state_id' => 68],
            ['id' => 305, 'name' => 'El Guamo', 'state_id' => 13],
            ['id' => 306, 'name' => 'El Molino', 'state_id' => 44],
            ['id' => 307, 'name' => 'El Paso', 'state_id' => 20],
            ['id' => 308, 'name' => 'El Paujil', 'state_id' => 18],
            ['id' => 309, 'name' => 'El Peñol', 'state_id' => 52],
            ['id' => 310, 'name' => 'El Peñon', 'state_id' => 13],
            ['id' => 311, 'name' => 'El Peñon', 'state_id' => 68],
            ['id' => 312, 'name' => 'El Peñón', 'state_id' => 25],
            ['id' => 313, 'name' => 'El Piñon', 'state_id' => 47],
            ['id' => 314, 'name' => 'El Playón', 'state_id' => 68],
            ['id' => 315, 'name' => 'El Retorno', 'state_id' => 95],
            ['id' => 316, 'name' => 'El Retén', 'state_id' => 47],
            ['id' => 317, 'name' => 'El Roble', 'state_id' => 70],
            ['id' => 318, 'name' => 'El Rosal', 'state_id' => 25],
            ['id' => 319, 'name' => 'El Rosario', 'state_id' => 52],
            ['id' => 320, 'name' => 'El Tablón de Gómez', 'state_id' => 52],
            ['id' => 321, 'name' => 'El Tambo', 'state_id' => 19],
            ['id' => 322, 'name' => 'El Tambo', 'state_id' => 52],
            ['id' => 323, 'name' => 'El Tarra', 'state_id' => 54],
            ['id' => 324, 'name' => 'El Zulia', 'state_id' => 54],
            ['id' => 325, 'name' => 'El Águila', 'state_id' => 76],
            ['id' => 326, 'name' => 'Elías', 'state_id' => 41],
            ['id' => 327, 'name' => 'Encino', 'state_id' => 68],
            ['id' => 328, 'name' => 'Enciso', 'state_id' => 68],
            ['id' => 329, 'name' => 'Entrerríos', 'state_id' => 5],
            ['id' => 330, 'name' => 'Envigado', 'state_id' => 5],
            ['id' => 331, 'name' => 'Espinal', 'state_id' => 73],
            ['id' => 332, 'name' => 'Facatativá', 'state_id' => 25],
            ['id' => 333, 'name' => 'Falan', 'state_id' => 73],
            ['id' => 334, 'name' => 'Filadelfia', 'state_id' => 17],
            ['id' => 335, 'name' => 'Filandia', 'state_id' => 63],
            ['id' => 336, 'name' => 'Firavitoba', 'state_id' => 15],
            ['id' => 337, 'name' => 'Flandes', 'state_id' => 73],
            ['id' => 338, 'name' => 'Florencia', 'state_id' => 18],
            ['id' => 339, 'name' => 'Florencia', 'state_id' => 19],
            ['id' => 340, 'name' => 'Floresta', 'state_id' => 15],
            ['id' => 341, 'name' => 'Florida', 'state_id' => 76],
            ['id' => 342, 'name' => 'Floridablanca', 'state_id' => 68],
            ['id' => 343, 'name' => 'Florián', 'state_id' => 68],
            ['id' => 344, 'name' => 'Fonseca', 'state_id' => 44],
            ['id' => 345, 'name' => 'Fortúl', 'state_id' => 81],
            ['id' => 346, 'name' => 'Fosca', 'state_id' => 25],
            ['id' => 347, 'name' => 'Francisco Pizarro', 'state_id' => 52],
            ['id' => 348, 'name' => 'Fredonia', 'state_id' => 5],
            ['id' => 349, 'name' => 'Fresno', 'state_id' => 73],
            ['id' => 350, 'name' => 'Frontino', 'state_id' => 5],
            ['id' => 351, 'name' => 'Fuente de Oro', 'state_id' => 50],
            ['id' => 352, 'name' => 'Fundación', 'state_id' => 47],
            ['id' => 353, 'name' => 'Funes', 'state_id' => 52],
            ['id' => 354, 'name' => 'Funza', 'state_id' => 25],
            ['id' => 355, 'name' => 'Fusagasugá', 'state_id' => 25],
            ['id' => 356, 'name' => 'Fómeque', 'state_id' => 25],
            ['id' => 357, 'name' => 'Fúquene', 'state_id' => 25],
            ['id' => 358, 'name' => 'Gachalá', 'state_id' => 25],
            ['id' => 359, 'name' => 'Gachancipá', 'state_id' => 25],
            ['id' => 360, 'name' => 'Gachantivá', 'state_id' => 15],
            ['id' => 361, 'name' => 'Gachetá', 'state_id' => 25],
            ['id' => 362, 'name' => 'Galapa', 'state_id' => 8],
            ['id' => 363, 'name' => 'Galeras (Nueva Granada)', 'state_id' => 70],
            ['id' => 364, 'name' => 'Galán', 'state_id' => 68],
            ['id' => 365, 'name' => 'Gama', 'state_id' => 25],
            ['id' => 366, 'name' => 'Gamarra', 'state_id' => 20],
            ['id' => 367, 'name' => 'Garagoa', 'state_id' => 15],
            ['id' => 368, 'name' => 'Garzón', 'state_id' => 41],
            ['id' => 369, 'name' => 'Gigante', 'state_id' => 41],
            ['id' => 370, 'name' => 'Ginebra', 'state_id' => 76],
            ['id' => 371, 'name' => 'Giraldo', 'state_id' => 5],
            ['id' => 372, 'name' => 'Girardot', 'state_id' => 25],
            ['id' => 373, 'name' => 'Girardota', 'state_id' => 5],
            ['id' => 374, 'name' => 'Girón', 'state_id' => 68],
            ['id' => 375, 'name' => 'Gonzalez', 'state_id' => 20],
            ['id' => 376, 'name' => 'Gramalote', 'state_id' => 54],
            ['id' => 377, 'name' => 'Granada', 'state_id' => 5],
            ['id' => 378, 'name' => 'Granada', 'state_id' => 25],
            ['id' => 379, 'name' => 'Granada', 'state_id' => 50],
            ['id' => 380, 'name' => 'Guaca', 'state_id' => 68],
            ['id' => 381, 'name' => 'Guacamayas', 'state_id' => 15],
            ['id' => 382, 'name' => 'Guacarí', 'state_id' => 76],
            ['id' => 383, 'name' => 'Guachavés', 'state_id' => 52],
            ['id' => 384, 'name' => 'Guachené', 'state_id' => 19],
            ['id' => 385, 'name' => 'Guachetá', 'state_id' => 25],
            ['id' => 386, 'name' => 'Guachucal', 'state_id' => 52],
            ['id' => 387, 'name' => 'Guadalupe', 'state_id' => 5],
            ['id' => 388, 'name' => 'Guadalupe', 'state_id' => 41],
            ['id' => 389, 'name' => 'Guadalupe', 'state_id' => 68],
            ['id' => 390, 'name' => 'Guaduas', 'state_id' => 25],
            ['id' => 391, 'name' => 'Guaitarilla', 'state_id' => 52],
            ['id' => 392, 'name' => 'Gualmatán', 'state_id' => 52],
            ['id' => 393, 'name' => 'Guamal', 'state_id' => 47],
            ['id' => 394, 'name' => 'Guamal', 'state_id' => 50],
            ['id' => 395, 'name' => 'Guamo', 'state_id' => 73],
            ['id' => 396, 'name' => 'Guapota', 'state_id' => 68],
            ['id' => 397, 'name' => 'Guapí', 'state_id' => 19],
            ['id' => 398, 'name' => 'Guaranda', 'state_id' => 70],
            ['id' => 399, 'name' => 'Guarne', 'state_id' => 5],
            ['id' => 400, 'name' => 'Guasca', 'state_id' => 25],
            ['id' => 401, 'name' => 'Guatapé', 'state_id' => 5],
            ['id' => 402, 'name' => 'Guataquí', 'state_id' => 25],
            ['id' => 403, 'name' => 'Guatavita', 'state_id' => 25],
            ['id' => 404, 'name' => 'Guateque', 'state_id' => 15],
            ['id' => 405, 'name' => 'Guavatá', 'state_id' => 68],
            ['id' => 406, 'name' => 'Guayabal de Siquima', 'state_id' => 25],
            ['id' => 407, 'name' => 'Guayabetal', 'state_id' => 25],
            ['id' => 408, 'name' => 'Guayatá', 'state_id' => 15],
            ['id' => 409, 'name' => 'Guepsa', 'state_id' => 68],
            ['id' => 410, 'name' => 'Guicán', 'state_id' => 15],
            ['id' => 411, 'name' => 'Gutiérrez', 'state_id' => 25],
            ['id' => 412, 'name' => 'Guática', 'state_id' => 66],
            ['id' => 413, 'name' => 'Gámbita', 'state_id' => 68],
            ['id' => 414, 'name' => 'Gámeza', 'state_id' => 15],
            ['id' => 415, 'name' => 'Génova', 'state_id' => 63],
            ['id' => 416, 'name' => 'Gómez Plata', 'state_id' => 5],
            ['id' => 417, 'name' => 'Hacarí', 'state_id' => 54],
            ['id' => 418, 'name' => 'Hatillo de Loba', 'state_id' => 13],
            ['id' => 419, 'name' => 'Hato', 'state_id' => 68],
            ['id' => 420, 'name' => 'Hato Corozal', 'state_id' => 85],
            ['id' => 421, 'name' => 'Hatonuevo', 'state_id' => 44],
            ['id' => 422, 'name' => 'Heliconia', 'state_id' => 5],
            ['id' => 423, 'name' => 'Herrán', 'state_id' => 54],
            ['id' => 424, 'name' => 'Herveo', 'state_id' => 73],
            ['id' => 425, 'name' => 'Hispania', 'state_id' => 5],
            ['id' => 426, 'name' => 'Hobo', 'state_id' => 41],
            ['id' => 427, 'name' => 'Honda', 'state_id' => 73],
            ['id' => 428, 'name' => 'Ibagué', 'state_id' => 73],
            ['id' => 429, 'name' => 'Icononzo', 'state_id' => 73],
            ['id' => 430, 'name' => 'Iles', 'state_id' => 52],
            ['id' => 431, 'name' => 'Imúes', 'state_id' => 52],
            ['id' => 432, 'name' => 'Inzá', 'state_id' => 19],
            ['id' => 433, 'name' => 'Inírida', 'state_id' => 94],
            ['id' => 434, 'name' => 'Ipiales', 'state_id' => 52],
            ['id' => 435, 'name' => 'Isnos', 'state_id' => 41],
            ['id' => 436, 'name' => 'Istmina', 'state_id' => 27],
            ['id' => 437, 'name' => 'Itagüí', 'state_id' => 5],
            ['id' => 438, 'name' => 'Ituango', 'state_id' => 5],
            ['id' => 439, 'name' => 'Izá', 'state_id' => 15],
            ['id' => 440, 'name' => 'Jambaló', 'state_id' => 19],
            ['id' => 441, 'name' => 'Jamundí', 'state_id' => 76],
            ['id' => 442, 'name' => 'Jardín', 'state_id' => 5],
            ['id' => 443, 'name' => 'Jenesano', 'state_id' => 15],
            ['id' => 444, 'name' => 'Jericó', 'state_id' => 5],
            ['id' => 445, 'name' => 'Jericó', 'state_id' => 15],
            ['id' => 446, 'name' => 'Jerusalén', 'state_id' => 25],
            ['id' => 447, 'name' => 'Jesús María', 'state_id' => 68],
            ['id' => 448, 'name' => 'Jordán', 'state_id' => 68],
            ['id' => 449, 'name' => 'Juan de Acosta', 'state_id' => 8],
            ['id' => 450, 'name' => 'Junín', 'state_id' => 25],
            ['id' => 451, 'name' => 'Juradó', 'state_id' => 27],
            ['id' => 452, 'name' => 'La Apartada y La Frontera', 'state_id' => 23],
            ['id' => 453, 'name' => 'La Argentina', 'state_id' => 41],
            ['id' => 454, 'name' => 'La Belleza', 'state_id' => 68],
            ['id' => 455, 'name' => 'La Calera', 'state_id' => 25],
            ['id' => 456, 'name' => 'La Capilla', 'state_id' => 15],
            ['id' => 457, 'name' => 'La Ceja', 'state_id' => 5],
            ['id' => 458, 'name' => 'La Celia', 'state_id' => 66],
            ['id' => 459, 'name' => 'La Cruz', 'state_id' => 52],
            ['id' => 460, 'name' => 'La Cumbre', 'state_id' => 76],
            ['id' => 461, 'name' => 'La Dorada', 'state_id' => 17],
            ['id' => 462, 'name' => 'La Esperanza', 'state_id' => 54],
            ['id' => 463, 'name' => 'La Estrella', 'state_id' => 5],
            ['id' => 464, 'name' => 'La Florida', 'state_id' => 52],
            ['id' => 465, 'name' => 'La Gloria', 'state_id' => 20],
            ['id' => 466, 'name' => 'La Jagua de Ibirico', 'state_id' => 20],
            ['id' => 467, 'name' => 'La Jagua del Pilar', 'state_id' => 44],
            ['id' => 468, 'name' => 'La Llanada', 'state_id' => 52],
            ['id' => 469, 'name' => 'La Macarena', 'state_id' => 50],
            ['id' => 470, 'name' => 'La Merced', 'state_id' => 17],
            ['id' => 471, 'name' => 'La Mesa', 'state_id' => 25],
            ['id' => 472, 'name' => 'La Montañita', 'state_id' => 18],
            ['id' => 473, 'name' => 'La Palma', 'state_id' => 25],
            ['id' => 474, 'name' => 'La Paz', 'state_id' => 68],
            ['id' => 475, 'name' => 'La Paz (Robles)', 'state_id' => 20],
            ['id' => 476, 'name' => 'La Peña', 'state_id' => 25],
            ['id' => 477, 'name' => 'La Pintada', 'state_id' => 5],
            ['id' => 478, 'name' => 'La Plata', 'state_id' => 41],
            ['id' => 479, 'name' => 'La Playa', 'state_id' => 54],
            ['id' => 480, 'name' => 'La Primavera', 'state_id' => 99],
            ['id' => 481, 'name' => 'La Salina', 'state_id' => 85],
            ['id' => 482, 'name' => 'La Sierra', 'state_id' => 19],
            ['id' => 483, 'name' => 'La Tebaida', 'state_id' => 63],
            ['id' => 484, 'name' => 'La Tola', 'state_id' => 52],
            ['id' => 485, 'name' => 'La Unión', 'state_id' => 5],
            ['id' => 486, 'name' => 'La Unión', 'state_id' => 52],
            ['id' => 487, 'name' => 'La Unión', 'state_id' => 70],
            ['id' => 488, 'name' => 'La Unión', 'state_id' => 76],
            ['id' => 489, 'name' => 'La Uvita', 'state_id' => 15],
            ['id' => 490, 'name' => 'La Vega', 'state_id' => 19],
            ['id' => 491, 'name' => 'La Vega', 'state_id' => 25],
            ['id' => 492, 'name' => 'La Victoria', 'state_id' => 15],
            ['id' => 493, 'name' => 'La Victoria', 'state_id' => 17],
            ['id' => 494, 'name' => 'La Victoria', 'state_id' => 76],
            ['id' => 495, 'name' => 'La Virginia', 'state_id' => 66],
            ['id' => 496, 'name' => 'Labateca', 'state_id' => 54],
            ['id' => 497, 'name' => 'Labranzagrande', 'state_id' => 15],
            ['id' => 498, 'name' => 'Landázuri', 'state_id' => 68],
            ['id' => 499, 'name' => 'Lebrija', 'state_id' => 68],
            ['id' => 500, 'name' => 'Leiva', 'state_id' => 52],
            ['id' => 501, 'name' => 'Lejanías', 'state_id' => 50],
            ['id' => 502, 'name' => 'Lenguazaque', 'state_id' => 25],
            ['id' => 503, 'name' => 'Leticia', 'state_id' => 91],
            ['id' => 504, 'name' => 'Liborina', 'state_id' => 5],
            ['id' => 505, 'name' => 'Linares', 'state_id' => 52],
            ['id' => 506, 'name' => 'Lloró', 'state_id' => 27],
            ['id' => 507, 'name' => 'Lorica', 'state_id' => 23],
            ['id' => 508, 'name' => 'Los Córdobas', 'state_id' => 23],
            ['id' => 509, 'name' => 'Los Palmitos', 'state_id' => 70],
            ['id' => 510, 'name' => 'Los Patios', 'state_id' => 54],
            ['id' => 511, 'name' => 'Los Santos', 'state_id' => 68],
            ['id' => 512, 'name' => 'Lourdes', 'state_id' => 54],
            ['id' => 513, 'name' => 'Luruaco', 'state_id' => 8],
            ['id' => 514, 'name' => 'Lérida', 'state_id' => 73],
            ['id' => 515, 'name' => 'Líbano', 'state_id' => 73],
            ['id' => 516, 'name' => 'López (Micay)', 'state_id' => 19],
            ['id' => 517, 'name' => 'Macanal', 'state_id' => 15],
            ['id' => 518, 'name' => 'Macaravita', 'state_id' => 68],
            ['id' => 519, 'name' => 'Maceo', 'state_id' => 5],
            ['id' => 520, 'name' => 'Machetá', 'state_id' => 25],
            ['id' => 521, 'name' => 'Madrid', 'state_id' => 25],
            ['id' => 522, 'name' => 'Magangué', 'state_id' => 13],
            ['id' => 523, 'name' => 'Magüi (Payán)', 'state_id' => 52],
            ['id' => 524, 'name' => 'Mahates', 'state_id' => 13],
            ['id' => 525, 'name' => 'Maicao', 'state_id' => 44],
            ['id' => 526, 'name' => 'Majagual', 'state_id' => 70],
            ['id' => 527, 'name' => 'Malambo', 'state_id' => 8],
            ['id' => 528, 'name' => 'Mallama (Piedrancha)', 'state_id' => 52],
            ['id' => 529, 'name' => 'Manatí', 'state_id' => 8],
            ['id' => 530, 'name' => 'Manaure', 'state_id' => 44],
            ['id' => 531, 'name' => 'Manaure Balcón del Cesar', 'state_id' => 20],
            ['id' => 532, 'name' => 'Manizales', 'state_id' => 17],
            ['id' => 533, 'name' => 'Manta', 'state_id' => 25],
            ['id' => 534, 'name' => 'Manzanares', 'state_id' => 17],
            ['id' => 535, 'name' => 'Maní', 'state_id' => 85],
            ['id' => 536, 'name' => 'Mapiripan', 'state_id' => 50],
            ['id' => 537, 'name' => 'Margarita', 'state_id' => 13],
            ['id' => 538, 'name' => 'Marinilla', 'state_id' => 5],
            ['id' => 539, 'name' => 'Maripí', 'state_id' => 15],
            ['id' => 540, 'name' => 'Mariquita', 'state_id' => 73],
            ['id' => 541, 'name' => 'Marmato', 'state_id' => 17],
            ['id' => 542, 'name' => 'Marquetalia', 'state_id' => 17],
            ['id' => 543, 'name' => 'Marsella', 'state_id' => 66],
            ['id' => 544, 'name' => 'Marulanda', 'state_id' => 17],
            ['id' => 545, 'name' => 'María la Baja', 'state_id' => 13],
            ['id' => 546, 'name' => 'Matanza', 'state_id' => 68],
            ['id' => 547, 'name' => 'Medellín', 'state_id' => 5],
            ['id' => 548, 'name' => 'Medina', 'state_id' => 25],
            ['id' => 549, 'name' => 'Medio Atrato', 'state_id' => 27],
            ['id' => 550, 'name' => 'Medio Baudó', 'state_id' => 27],
            ['id' => 551, 'name' => 'Medio San Juan (ANDAGOYA)', 'state_id' => 27],
            ['id' => 552, 'name' => 'Melgar', 'state_id' => 73],
            ['id' => 553, 'name' => 'Mercaderes', 'state_id' => 19],
            ['id' => 554, 'name' => 'Mesetas', 'state_id' => 50],
            ['id' => 555, 'name' => 'Milán', 'state_id' => 18],
            ['id' => 556, 'name' => 'Miraflores', 'state_id' => 15],
            ['id' => 557, 'name' => 'Miraflores', 'state_id' => 95],
            ['id' => 558, 'name' => 'Miranda', 'state_id' => 19],
            ['id' => 559, 'name' => 'Mistrató', 'state_id' => 66],
            ['id' => 560, 'name' => 'Mitú', 'state_id' => 97],
            ['id' => 561, 'name' => 'Mocoa', 'state_id' => 86],
            ['id' => 562, 'name' => 'Mogotes', 'state_id' => 68],
            ['id' => 563, 'name' => 'Molagavita', 'state_id' => 68],
            ['id' => 564, 'name' => 'Momil', 'state_id' => 23],
            ['id' => 565, 'name' => 'Mompós', 'state_id' => 13],
            ['id' => 566, 'name' => 'Mongua', 'state_id' => 15],
            ['id' => 567, 'name' => 'Monguí', 'state_id' => 15],
            ['id' => 568, 'name' => 'Moniquirá', 'state_id' => 15],
            ['id' => 569, 'name' => 'Montebello', 'state_id' => 5],
            ['id' => 570, 'name' => 'Montecristo', 'state_id' => 13],
            ['id' => 571, 'name' => 'Montelíbano', 'state_id' => 23],
            ['id' => 572, 'name' => 'Montenegro', 'state_id' => 63],
            ['id' => 573, 'name' => 'Monteria', 'state_id' => 23],
            ['id' => 574, 'name' => 'Monterrey', 'state_id' => 85],
            ['id' => 575, 'name' => 'Morales', 'state_id' => 13],
            ['id' => 576, 'name' => 'Morales', 'state_id' => 19],
            ['id' => 577, 'name' => 'Morelia', 'state_id' => 18],
            ['id' => 578, 'name' => 'Morroa', 'state_id' => 70],
            ['id' => 579, 'name' => 'Mosquera', 'state_id' => 25],
            ['id' => 580, 'name' => 'Mosquera', 'state_id' => 52],
            ['id' => 581, 'name' => 'Motavita', 'state_id' => 15],
            ['id' => 582, 'name' => 'Moñitos', 'state_id' => 23],
            ['id' => 583, 'name' => 'Murillo', 'state_id' => 73],
            ['id' => 584, 'name' => 'Murindó', 'state_id' => 5],
            ['id' => 585, 'name' => 'Mutatá', 'state_id' => 5],
            ['id' => 586, 'name' => 'Mutiscua', 'state_id' => 54],
            ['id' => 587, 'name' => 'Muzo', 'state_id' => 15],
            ['id' => 588, 'name' => 'Málaga', 'state_id' => 68],
            ['id' => 589, 'name' => 'Nariño', 'state_id' => 5],
            ['id' => 590, 'name' => 'Nariño', 'state_id' => 25],
            ['id' => 591, 'name' => 'Nariño', 'state_id' => 52],
            ['id' => 592, 'name' => 'Natagaima', 'state_id' => 73],
            ['id' => 593, 'name' => 'Nechí', 'state_id' => 5],
            ['id' => 594, 'name' => 'Necoclí', 'state_id' => 5],
            ['id' => 595, 'name' => 'Neira', 'state_id' => 17],
            ['id' => 596, 'name' => 'Neiva', 'state_id' => 41],
            ['id' => 597, 'name' => 'Nemocón', 'state_id' => 25],
            ['id' => 598, 'name' => 'Nilo', 'state_id' => 25],
            ['id' => 599, 'name' => 'Nimaima', 'state_id' => 25],
            ['id' => 600, 'name' => 'Nobsa', 'state_id' => 15],
            ['id' => 601, 'name' => 'Nocaima', 'state_id' => 25],
            ['id' => 602, 'name' => 'Norcasia', 'state_id' => 17],
            ['id' => 603, 'name' => 'Norosí', 'state_id' => 13],
            ['id' => 604, 'name' => 'Novita', 'state_id' => 27],
            ['id' => 605, 'name' => 'Nueva Granada', 'state_id' => 47],
            ['id' => 606, 'name' => 'Nuevo Colón', 'state_id' => 15],
            ['id' => 607, 'name' => 'Nunchía', 'state_id' => 85],
            ['id' => 608, 'name' => 'Nuquí', 'state_id' => 27],
            ['id' => 609, 'name' => 'Nátaga', 'state_id' => 41],
            ['id' => 610, 'name' => 'Obando', 'state_id' => 76],
            ['id' => 611, 'name' => 'Ocamonte', 'state_id' => 68],
            ['id' => 612, 'name' => 'Ocaña', 'state_id' => 54],
            ['id' => 613, 'name' => 'Oiba', 'state_id' => 68],
            ['id' => 614, 'name' => 'Oicatá', 'state_id' => 15],
            ['id' => 615, 'name' => 'Olaya', 'state_id' => 5],
            ['id' => 616, 'name' => 'Olaya Herrera', 'state_id' => 52],
            ['id' => 617, 'name' => 'Onzaga', 'state_id' => 68],
            ['id' => 618, 'name' => 'Oporapa', 'state_id' => 41],
            ['id' => 619, 'name' => 'Orito', 'state_id' => 86],
            ['id' => 620, 'name' => 'Orocué', 'state_id' => 85],
            ['id' => 621, 'name' => 'Ortega', 'state_id' => 73],
            ['id' => 622, 'name' => 'Ospina', 'state_id' => 52],
            ['id' => 623, 'name' => 'Otanche', 'state_id' => 15],
            ['id' => 624, 'name' => 'Ovejas', 'state_id' => 70],
            ['id' => 625, 'name' => 'Pachavita', 'state_id' => 15],
            ['id' => 626, 'name' => 'Pacho', 'state_id' => 25],
            ['id' => 627, 'name' => 'Padilla', 'state_id' => 19],
            ['id' => 628, 'name' => 'Paicol', 'state_id' => 41],
            ['id' => 629, 'name' => 'Pailitas', 'state_id' => 20],
            ['id' => 630, 'name' => 'Paime', 'state_id' => 25],
            ['id' => 631, 'name' => 'Paipa', 'state_id' => 15],
            ['id' => 632, 'name' => 'Pajarito', 'state_id' => 15],
            ['id' => 633, 'name' => 'Palermo', 'state_id' => 41],
            ['id' => 634, 'name' => 'Palestina', 'state_id' => 17],
            ['id' => 635, 'name' => 'Palestina', 'state_id' => 41],
            ['id' => 636, 'name' => 'Palmar', 'state_id' => 68],
            ['id' => 637, 'name' => 'Palmar de Varela', 'state_id' => 8],
            ['id' => 638, 'name' => 'Palmas del Socorro', 'state_id' => 68],
            ['id' => 639, 'name' => 'Palmira', 'state_id' => 76],
            ['id' => 640, 'name' => 'Palmito', 'state_id' => 70],
            ['id' => 641, 'name' => 'Palocabildo', 'state_id' => 73],
            ['id' => 642, 'name' => 'Pamplona', 'state_id' => 54],
            ['id' => 643, 'name' => 'Pamplonita', 'state_id' => 54],
            ['id' => 644, 'name' => 'Pandi', 'state_id' => 25],
            ['id' => 645, 'name' => 'Panqueba', 'state_id' => 15],
            ['id' => 646, 'name' => 'Paratebueno', 'state_id' => 25],
            ['id' => 647, 'name' => 'Pasca', 'state_id' => 25],
            ['id' => 648, 'name' => 'Patía (El Bordo)', 'state_id' => 19],
            ['id' => 649, 'name' => 'Pauna', 'state_id' => 15],
            ['id' => 650, 'name' => 'Paya', 'state_id' => 15],
            ['id' => 651, 'name' => 'Paz de Ariporo', 'state_id' => 85],
            ['id' => 652, 'name' => 'Paz de Río', 'state_id' => 15],
            ['id' => 653, 'name' => 'Pedraza', 'state_id' => 47],
            ['id' => 654, 'name' => 'Pelaya', 'state_id' => 20],
            ['id' => 655, 'name' => 'Pensilvania', 'state_id' => 17],
            ['id' => 656, 'name' => 'Peque', 'state_id' => 5],
            ['id' => 657, 'name' => 'Pereira', 'state_id' => 66],
            ['id' => 658, 'name' => 'Pesca', 'state_id' => 15],
            ['id' => 659, 'name' => 'Peñol', 'state_id' => 5],
            ['id' => 660, 'name' => 'Piamonte', 'state_id' => 19],
            ['id' => 661, 'name' => 'Pie de Cuesta', 'state_id' => 68],
            ['id' => 662, 'name' => 'Piedras', 'state_id' => 73],
            ['id' => 663, 'name' => 'Piendamó', 'state_id' => 19],
            ['id' => 664, 'name' => 'Pijao', 'state_id' => 63],
            ['id' => 665, 'name' => 'Pijiño', 'state_id' => 47],
            ['id' => 666, 'name' => 'Pinchote', 'state_id' => 68],
            ['id' => 667, 'name' => 'Pinillos', 'state_id' => 13],
            ['id' => 668, 'name' => 'Piojo', 'state_id' => 8],
            ['id' => 669, 'name' => 'Pisva', 'state_id' => 15],
            ['id' => 670, 'name' => 'Pital', 'state_id' => 41],
            ['id' => 671, 'name' => 'Pitalito', 'state_id' => 41],
            ['id' => 672, 'name' => 'Pivijay', 'state_id' => 47],
            ['id' => 673, 'name' => 'Planadas', 'state_id' => 73],
            ['id' => 674, 'name' => 'Planeta Rica', 'state_id' => 23],
            ['id' => 675, 'name' => 'Plato', 'state_id' => 47],
            ['id' => 676, 'name' => 'Policarpa', 'state_id' => 52],
            ['id' => 677, 'name' => 'Polonuevo', 'state_id' => 8],
            ['id' => 678, 'name' => 'Ponedera', 'state_id' => 8],
            ['id' => 679, 'name' => 'Popayán', 'state_id' => 19],
            ['id' => 680, 'name' => 'Pore', 'state_id' => 85],
            ['id' => 681, 'name' => 'Potosí', 'state_id' => 52],
            ['id' => 682, 'name' => 'Pradera', 'state_id' => 76],
            ['id' => 683, 'name' => 'Prado', 'state_id' => 73],
            ['id' => 684, 'name' => 'Providencia', 'state_id' => 52],
            ['id' => 685, 'name' => 'Providencia', 'state_id' => 88],
            ['id' => 686, 'name' => 'Pueblo Bello', 'state_id' => 20],
            ['id' => 687, 'name' => 'Pueblo Nuevo', 'state_id' => 23],
            ['id' => 688, 'name' => 'Pueblo Rico', 'state_id' => 66],
            ['id' => 689, 'name' => 'Pueblorrico', 'state_id' => 5],
            ['id' => 690, 'name' => 'Puebloviejo', 'state_id' => 47],
            ['id' => 691, 'name' => 'Puente Nacional', 'state_id' => 68],
            ['id' => 692, 'name' => 'Puerres', 'state_id' => 52],
            ['id' => 693, 'name' => 'Puerto Asís', 'state_id' => 86],
            ['id' => 694, 'name' => 'Puerto Berrío', 'state_id' => 5],
            ['id' => 695, 'name' => 'Puerto Boyacá', 'state_id' => 15],
            ['id' => 696, 'name' => 'Puerto Caicedo', 'state_id' => 86],
            ['id' => 697, 'name' => 'Puerto Carreño', 'state_id' => 99],
            ['id' => 698, 'name' => 'Puerto Colombia', 'state_id' => 8],
            ['id' => 699, 'name' => 'Puerto Concordia', 'state_id' => 50],
            ['id' => 700, 'name' => 'Puerto Escondido', 'state_id' => 23],
            ['id' => 701, 'name' => 'Puerto Gaitán', 'state_id' => 50],
            ['id' => 702, 'name' => 'Puerto Guzmán', 'state_id' => 86],
            ['id' => 703, 'name' => 'Puerto Leguízamo', 'state_id' => 86],
            ['id' => 704, 'name' => 'Puerto Libertador', 'state_id' => 23],
            ['id' => 705, 'name' => 'Puerto Lleras', 'state_id' => 50],
            ['id' => 706, 'name' => 'Puerto López', 'state_id' => 50],
            ['id' => 707, 'name' => 'Puerto Nare', 'state_id' => 5],
            ['id' => 708, 'name' => 'Puerto Nariño', 'state_id' => 91],
            ['id' => 709, 'name' => 'Puerto Parra', 'state_id' => 68],
            ['id' => 710, 'name' => 'Puerto Rico', 'state_id' => 18],
            ['id' => 711, 'name' => 'Puerto Rico', 'state_id' => 50],
            ['id' => 712, 'name' => 'Puerto Rondón', 'state_id' => 81],
            ['id' => 713, 'name' => 'Puerto Salgar', 'state_id' => 25],
            ['id' => 714, 'name' => 'Puerto Santander', 'state_id' => 54],
            ['id' => 715, 'name' => 'Puerto Tejada', 'state_id' => 19],
            ['id' => 716, 'name' => 'Puerto Triunfo', 'state_id' => 5],
            ['id' => 717, 'name' => 'Puerto Wilches', 'state_id' => 68],
            ['id' => 718, 'name' => 'Pulí', 'state_id' => 25],
            ['id' => 719, 'name' => 'Pupiales', 'state_id' => 52],
            ['id' => 720, 'name' => 'Puracé (Coconuco)', 'state_id' => 19],
            ['id' => 721, 'name' => 'Purificación', 'state_id' => 73],
            ['id' => 722, 'name' => 'Purísima', 'state_id' => 23],
            ['id' => 723, 'name' => 'Pácora', 'state_id' => 17],
            ['id' => 724, 'name' => 'Páez', 'state_id' => 15],
            ['id' => 725, 'name' => 'Páez (Belalcazar)', 'state_id' => 19],
            ['id' => 726, 'name' => 'Páramo', 'state_id' => 68],
            ['id' => 727, 'name' => 'Quebradanegra', 'state_id' => 25],
            ['id' => 728, 'name' => 'Quetame', 'state_id' => 25],
            ['id' => 729, 'name' => 'Quibdó', 'state_id' => 27],
            ['id' => 730, 'name' => 'Quimbaya', 'state_id' => 63],
            ['id' => 731, 'name' => 'Quinchía', 'state_id' => 66],
            ['id' => 732, 'name' => 'Quipama', 'state_id' => 15],
            ['id' => 733, 'name' => 'Quipile', 'state_id' => 25],
            ['id' => 734, 'name' => 'Ragonvalia', 'state_id' => 54],
            ['id' => 735, 'name' => 'Ramiriquí', 'state_id' => 15],
            ['id' => 736, 'name' => 'Recetor', 'state_id' => 85],
            ['id' => 737, 'name' => 'Regidor', 'state_id' => 13],
            ['id' => 738, 'name' => 'Remedios', 'state_id' => 5],
            ['id' => 739, 'name' => 'Remolino', 'state_id' => 47],
            ['id' => 740, 'name' => 'Repelón', 'state_id' => 8],
            ['id' => 741, 'name' => 'Restrepo', 'state_id' => 50],
            ['id' => 742, 'name' => 'Restrepo', 'state_id' => 76],
            ['id' => 743, 'name' => 'Retiro', 'state_id' => 5],
            ['id' => 744, 'name' => 'Ricaurte', 'state_id' => 25],
            ['id' => 745, 'name' => 'Ricaurte', 'state_id' => 52],
            ['id' => 746, 'name' => 'Rio Negro', 'state_id' => 68],
            ['id' => 747, 'name' => 'Rioblanco', 'state_id' => 73],
            ['id' => 748, 'name' => 'Riofrío', 'state_id' => 76],
            ['id' => 749, 'name' => 'Riohacha', 'state_id' => 44],
            ['id' => 750, 'name' => 'Risaralda', 'state_id' => 17],
            ['id' => 751, 'name' => 'Rivera', 'state_id' => 41],
            ['id' => 752, 'name' => 'Roberto Payán (San José)', 'state_id' => 52],
            ['id' => 753, 'name' => 'Roldanillo', 'state_id' => 76],
            ['id' => 754, 'name' => 'Roncesvalles', 'state_id' => 73],
            ['id' => 755, 'name' => 'Rondón', 'state_id' => 15],
            ['id' => 756, 'name' => 'Rosas', 'state_id' => 19],
            ['id' => 757, 'name' => 'Rovira', 'state_id' => 73],
            ['id' => 758, 'name' => 'Ráquira', 'state_id' => 15],
            ['id' => 759, 'name' => 'Río Iró', 'state_id' => 27],
            ['id' => 760, 'name' => 'Río Quito', 'state_id' => 27],
            ['id' => 761, 'name' => 'Río Sucio', 'state_id' => 17],
            ['id' => 762, 'name' => 'Río Viejo', 'state_id' => 13],
            ['id' => 763, 'name' => 'Río de oro', 'state_id' => 20],
            ['id' => 764, 'name' => 'Ríonegro', 'state_id' => 5],
            ['id' => 765, 'name' => 'Ríosucio', 'state_id' => 27],
            ['id' => 766, 'name' => 'Sabana de Torres', 'state_id' => 68],
            ['id' => 767, 'name' => 'Sabanagrande', 'state_id' => 8],
            ['id' => 768, 'name' => 'Sabanalarga', 'state_id' => 5],
            ['id' => 769, 'name' => 'Sabanalarga', 'state_id' => 8],
            ['id' => 770, 'name' => 'Sabanalarga', 'state_id' => 85],
            ['id' => 771, 'name' => 'Sabanas de San Angel (SAN ANGEL)', 'state_id' => 47],
            ['id' => 772, 'name' => 'Sabaneta', 'state_id' => 5],
            ['id' => 773, 'name' => 'Saboyá', 'state_id' => 15],
            ['id' => 774, 'name' => 'Sahagún', 'state_id' => 23],
            ['id' => 775, 'name' => 'Saladoblanco', 'state_id' => 41],
            ['id' => 776, 'name' => 'Salamina', 'state_id' => 17],
            ['id' => 777, 'name' => 'Salamina', 'state_id' => 47],
            ['id' => 778, 'name' => 'Salazar', 'state_id' => 54],
            ['id' => 779, 'name' => 'Saldaña', 'state_id' => 73],
            ['id' => 780, 'name' => 'Salento', 'state_id' => 63],
            ['id' => 781, 'name' => 'Salgar', 'state_id' => 5],
            ['id' => 782, 'name' => 'Samacá', 'state_id' => 15],
            ['id' => 783, 'name' => 'Samaniego', 'state_id' => 52],
            ['id' => 784, 'name' => 'Samaná', 'state_id' => 17],
            ['id' => 785, 'name' => 'Sampués', 'state_id' => 70],
            ['id' => 786, 'name' => 'San Agustín', 'state_id' => 41],
            ['id' => 787, 'name' => 'San Alberto', 'state_id' => 20],
            ['id' => 788, 'name' => 'San Andrés', 'state_id' => 68],
            ['id' => 789, 'name' => 'San Andrés Sotavento', 'state_id' => 23],
            ['id' => 790, 'name' => 'San Andrés de Cuerquía', 'state_id' => 5],
            ['id' => 791, 'name' => 'San Antero', 'state_id' => 23],
            ['id' => 792, 'name' => 'San Antonio', 'state_id' => 73],
            ['id' => 793, 'name' => 'San Antonio de Tequendama', 'state_id' => 25],
            ['id' => 794, 'name' => 'San Benito', 'state_id' => 68],
            ['id' => 795, 'name' => 'San Benito Abad', 'state_id' => 70],
            ['id' => 796, 'name' => 'San Bernardo', 'state_id' => 25],
            ['id' => 797, 'name' => 'San Bernardo', 'state_id' => 52],
            ['id' => 798, 'name' => 'San Bernardo del Viento', 'state_id' => 23],
            ['id' => 799, 'name' => 'San Calixto', 'state_id' => 54],
            ['id' => 800, 'name' => 'San Carlos', 'state_id' => 5],
            ['id' => 801, 'name' => 'San Carlos', 'state_id' => 23],
            ['id' => 802, 'name' => 'San Carlos de Guaroa', 'state_id' => 50],
            ['id' => 803, 'name' => 'San Cayetano', 'state_id' => 25],
            ['id' => 804, 'name' => 'San Cayetano', 'state_id' => 54],
            ['id' => 805, 'name' => 'San Cristobal', 'state_id' => 13],
            ['id' => 806, 'name' => 'San Diego', 'state_id' => 20],
            ['id' => 807, 'name' => 'San Eduardo', 'state_id' => 15],
            ['id' => 808, 'name' => 'San Estanislao', 'state_id' => 13],
            ['id' => 809, 'name' => 'San Fernando', 'state_id' => 13],
            ['id' => 810, 'name' => 'San Francisco', 'state_id' => 5],
            ['id' => 811, 'name' => 'San Francisco', 'state_id' => 25],
            ['id' => 812, 'name' => 'San Francisco', 'state_id' => 86],
            ['id' => 813, 'name' => 'San Gíl', 'state_id' => 68],
            ['id' => 814, 'name' => 'San Jacinto', 'state_id' => 13],
            ['id' => 815, 'name' => 'San Jacinto del Cauca', 'state_id' => 13],
            ['id' => 816, 'name' => 'San Jerónimo', 'state_id' => 5],
            ['id' => 817, 'name' => 'San Joaquín', 'state_id' => 68],
            ['id' => 818, 'name' => 'San José', 'state_id' => 17],
            ['id' => 819, 'name' => 'San José de Miranda', 'state_id' => 68],
            ['id' => 820, 'name' => 'San José de Montaña', 'state_id' => 5],
            ['id' => 821, 'name' => 'San José de Pare', 'state_id' => 15],
            ['id' => 822, 'name' => 'San José de Uré', 'state_id' => 23],
            ['id' => 823, 'name' => 'San José del Fragua', 'state_id' => 18],
            ['id' => 824, 'name' => 'San José del Guaviare', 'state_id' => 95],
            ['id' => 825, 'name' => 'San José del Palmar', 'state_id' => 27],
            ['id' => 826, 'name' => 'San Juan de Arama', 'state_id' => 50],
            ['id' => 827, 'name' => 'San Juan de Betulia', 'state_id' => 70],
            ['id' => 828, 'name' => 'San Juan de Nepomuceno', 'state_id' => 13],
            ['id' => 829, 'name' => 'San Juan de Pasto', 'state_id' => 52],
            ['id' => 830, 'name' => 'San Juan de Río Seco', 'state_id' => 25],
            ['id' => 831, 'name' => 'San Juan de Urabá', 'state_id' => 5],
            ['id' => 832, 'name' => 'San Juan del Cesar', 'state_id' => 44],
            ['id' => 833, 'name' => 'San Juanito', 'state_id' => 50],
            ['id' => 834, 'name' => 'San Lorenzo', 'state_id' => 52],
            ['id' => 835, 'name' => 'San Luis', 'state_id' => 73],
            ['id' => 836, 'name' => 'San Luís', 'state_id' => 5],
            ['id' => 837, 'name' => 'San Luís de Gaceno', 'state_id' => 15],
            ['id' => 838, 'name' => 'San Luís de Palenque', 'state_id' => 85],
            ['id' => 839, 'name' => 'San Marcos', 'state_id' => 70],
            ['id' => 840, 'name' => 'San Martín', 'state_id' => 20],
            ['id' => 841, 'name' => 'San Martín', 'state_id' => 50],
            ['id' => 842, 'name' => 'San Martín de Loba', 'state_id' => 13],
            ['id' => 843, 'name' => 'San Mateo', 'state_id' => 15],
            ['id' => 844, 'name' => 'San Miguel', 'state_id' => 68],
            ['id' => 845, 'name' => 'San Miguel', 'state_id' => 86],
            ['id' => 846, 'name' => 'San Miguel de Sema', 'state_id' => 15],
            ['id' => 847, 'name' => 'San Onofre', 'state_id' => 70],
            ['id' => 848, 'name' => 'San Pablo', 'state_id' => 13],
            ['id' => 849, 'name' => 'San Pablo', 'state_id' => 52],
            ['id' => 850, 'name' => 'San Pablo de Borbur', 'state_id' => 15],
            ['id' => 851, 'name' => 'San Pedro', 'state_id' => 5],
            ['id' => 852, 'name' => 'San Pedro', 'state_id' => 70],
            ['id' => 853, 'name' => 'San Pedro', 'state_id' => 76],
            ['id' => 854, 'name' => 'San Pedro de Cartago', 'state_id' => 52],
            ['id' => 855, 'name' => 'San Pedro de Urabá', 'state_id' => 5],
            ['id' => 856, 'name' => 'San Pelayo', 'state_id' => 23],
            ['id' => 857, 'name' => 'San Rafael', 'state_id' => 5],
            ['id' => 858, 'name' => 'San Roque', 'state_id' => 5],
            ['id' => 859, 'name' => 'San Sebastián', 'state_id' => 19],
            ['id' => 860, 'name' => 'San Sebastián de Buenavista', 'state_id' => 47],
            ['id' => 861, 'name' => 'San Vicente', 'state_id' => 5],
            ['id' => 862, 'name' => 'San Vicente del Caguán', 'state_id' => 18],
            ['id' => 863, 'name' => 'San Vicente del Chucurí', 'state_id' => 68],
            ['id' => 864, 'name' => 'San Zenón', 'state_id' => 47],
            ['id' => 865, 'name' => 'Sandoná', 'state_id' => 52],
            ['id' => 866, 'name' => 'Santa Ana', 'state_id' => 47],
            ['id' => 867, 'name' => 'Santa Bárbara', 'state_id' => 5],
            ['id' => 868, 'name' => 'Santa Bárbara', 'state_id' => 68],
            ['id' => 869, 'name' => 'Santa Bárbara (Iscuandé)', 'state_id' => 52],
            ['id' => 870, 'name' => 'Santa Bárbara de Pinto', 'state_id' => 47],
            ['id' => 871, 'name' => 'Santa Catalina', 'state_id' => 13],
            ['id' => 872, 'name' => 'Santa Fé de Antioquia', 'state_id' => 5],
            ['id' => 873, 'name' => 'Santa Genoveva de Docorodó', 'state_id' => 27],
            ['id' => 874, 'name' => 'Santa Helena del Opón', 'state_id' => 68],
            ['id' => 875, 'name' => 'Santa Isabel', 'state_id' => 73],
            ['id' => 876, 'name' => 'Santa Lucía', 'state_id' => 8],
            ['id' => 877, 'name' => 'Santa Marta', 'state_id' => 47],
            ['id' => 878, 'name' => 'Santa María', 'state_id' => 15],
            ['id' => 879, 'name' => 'Santa María', 'state_id' => 41],
            ['id' => 880, 'name' => 'Santa Rosa', 'state_id' => 13],
            ['id' => 881, 'name' => 'Santa Rosa', 'state_id' => 19],
            ['id' => 882, 'name' => 'Santa Rosa de Cabal', 'state_id' => 66],
            ['id' => 883, 'name' => 'Santa Rosa de Osos', 'state_id' => 5],
            ['id' => 884, 'name' => 'Santa Rosa de Viterbo', 'state_id' => 15],
            ['id' => 885, 'name' => 'Santa Rosa del Sur', 'state_id' => 13],
            ['id' => 886, 'name' => 'Santa Rosalía', 'state_id' => 99],
            ['id' => 887, 'name' => 'Santa Sofía', 'state_id' => 15],
            ['id' => 888, 'name' => 'Santana', 'state_id' => 15],
            ['id' => 889, 'name' => 'Santander de Quilichao', 'state_id' => 19],
            ['id' => 890, 'name' => 'Santiago', 'state_id' => 54],
            ['id' => 891, 'name' => 'Santiago', 'state_id' => 86],
            ['id' => 892, 'name' => 'Santo Domingo', 'state_id' => 5],
            ['id' => 893, 'name' => 'Santo Tomás', 'state_id' => 8],
            ['id' => 894, 'name' => 'Santuario', 'state_id' => 5],
            ['id' => 895, 'name' => 'Santuario', 'state_id' => 66],
            ['id' => 896, 'name' => 'Sapuyes', 'state_id' => 52],
            ['id' => 897, 'name' => 'Saravena', 'state_id' => 81],
            ['id' => 898, 'name' => 'Sardinata', 'state_id' => 54],
            ['id' => 899, 'name' => 'Sasaima', 'state_id' => 25],
            ['id' => 900, 'name' => 'Sativanorte', 'state_id' => 15],
            ['id' => 901, 'name' => 'Sativasur', 'state_id' => 15],
            ['id' => 902, 'name' => 'Segovia', 'state_id' => 5],
            ['id' => 903, 'name' => 'Sesquilé', 'state_id' => 25],
            ['id' => 904, 'name' => 'Sevilla', 'state_id' => 76],
            ['id' => 905, 'name' => 'Siachoque', 'state_id' => 15],
            ['id' => 906, 'name' => 'Sibaté', 'state_id' => 25],
            ['id' => 907, 'name' => 'Sibundoy', 'state_id' => 86],
            ['id' => 908, 'name' => 'Silos', 'state_id' => 54],
            ['id' => 909, 'name' => 'Silvania', 'state_id' => 25],
            ['id' => 910, 'name' => 'Silvia', 'state_id' => 19],
            ['id' => 911, 'name' => 'Simacota', 'state_id' => 68],
            ['id' => 912, 'name' => 'Simijaca', 'state_id' => 25],
            ['id' => 913, 'name' => 'Simití', 'state_id' => 13],
            ['id' => 914, 'name' => 'Sincelejo', 'state_id' => 70],
            ['id' => 915, 'name' => 'Sincé', 'state_id' => 70],
            ['id' => 916, 'name' => 'Sipí', 'state_id' => 27],
            ['id' => 917, 'name' => 'Sitionuevo', 'state_id' => 47],
            ['id' => 918, 'name' => 'Soacha', 'state_id' => 25],
            ['id' => 919, 'name' => 'Soatá', 'state_id' => 15],
            ['id' => 920, 'name' => 'Socha', 'state_id' => 15],
            ['id' => 921, 'name' => 'Socorro', 'state_id' => 68],
            ['id' => 922, 'name' => 'Socotá', 'state_id' => 15],
            ['id' => 923, 'name' => 'Sogamoso', 'state_id' => 15],
            ['id' => 924, 'name' => 'Solano', 'state_id' => 18],
            ['id' => 925, 'name' => 'Soledad', 'state_id' => 8],
            ['id' => 926, 'name' => 'Solita', 'state_id' => 18],
            ['id' => 927, 'name' => 'Somondoco', 'state_id' => 15],
            ['id' => 928, 'name' => 'Sonsón', 'state_id' => 5],
            ['id' => 929, 'name' => 'Sopetrán', 'state_id' => 5],
            ['id' => 930, 'name' => 'Soplaviento', 'state_id' => 13],
            ['id' => 931, 'name' => 'Sopó', 'state_id' => 25],
            ['id' => 932, 'name' => 'Sora', 'state_id' => 15],
            ['id' => 933, 'name' => 'Soracá', 'state_id' => 15],
            ['id' => 934, 'name' => 'Sotaquirá', 'state_id' => 15],
            ['id' => 935, 'name' => 'Sotara (Paispamba)', 'state_id' => 19],
            ['id' => 936, 'name' => 'Sotomayor (Los Andes)', 'state_id' => 52],
            ['id' => 937, 'name' => 'Suaita', 'state_id' => 68],
            ['id' => 938, 'name' => 'Suan', 'state_id' => 8],
            ['id' => 939, 'name' => 'Suaza', 'state_id' => 41],
            ['id' => 940, 'name' => 'Subachoque', 'state_id' => 25],
            ['id' => 941, 'name' => 'Sucre', 'state_id' => 19],
            ['id' => 942, 'name' => 'Sucre', 'state_id' => 68],
            ['id' => 943, 'name' => 'Sucre', 'state_id' => 70],
            ['id' => 944, 'name' => 'Suesca', 'state_id' => 25],
            ['id' => 945, 'name' => 'Supatá', 'state_id' => 25],
            ['id' => 946, 'name' => 'Supía', 'state_id' => 17],
            ['id' => 947, 'name' => 'Suratá', 'state_id' => 68],
            ['id' => 948, 'name' => 'Susa', 'state_id' => 25],
            ['id' => 949, 'name' => 'Susacón', 'state_id' => 15],
            ['id' => 950, 'name' => 'Sutamarchán', 'state_id' => 15],
            ['id' => 951, 'name' => 'Sutatausa', 'state_id' => 25],
            ['id' => 952, 'name' => 'Sutatenza', 'state_id' => 15],
            ['id' => 953, 'name' => 'Suárez', 'state_id' => 19],
            ['id' => 954, 'name' => 'Suárez', 'state_id' => 73],
            ['id' => 955, 'name' => 'Sácama', 'state_id' => 85],
            ['id' => 956, 'name' => 'Sáchica', 'state_id' => 15],
            ['id' => 957, 'name' => 'Tabio', 'state_id' => 25],
            ['id' => 958, 'name' => 'Tadó', 'state_id' => 27],
            ['id' => 959, 'name' => 'Talaigua Nuevo', 'state_id' => 13],
            ['id' => 960, 'name' => 'Tamalameque', 'state_id' => 20],
            ['id' => 961, 'name' => 'Tame', 'state_id' => 81],
            ['id' => 962, 'name' => 'Taminango', 'state_id' => 52],
            ['id' => 963, 'name' => 'Tangua', 'state_id' => 52],
            ['id' => 964, 'name' => 'Taraira', 'state_id' => 97],
            ['id' => 965, 'name' => 'Tarazá', 'state_id' => 5],
            ['id' => 966, 'name' => 'Tarqui', 'state_id' => 41],
            ['id' => 967, 'name' => 'Tarso', 'state_id' => 5],
            ['id' => 968, 'name' => 'Tasco', 'state_id' => 15],
            ['id' => 969, 'name' => 'Tauramena', 'state_id' => 85],
            ['id' => 970, 'name' => 'Tausa', 'state_id' => 25],
            ['id' => 971, 'name' => 'Tello', 'state_id' => 41],
            ['id' => 972, 'name' => 'Tena', 'state_id' => 25],
            ['id' => 973, 'name' => 'Tenerife', 'state_id' => 47],
            ['id' => 974, 'name' => 'Tenjo', 'state_id' => 25],
            ['id' => 975, 'name' => 'Tenza', 'state_id' => 15],
            ['id' => 976, 'name' => 'Teorama', 'state_id' => 54],
            ['id' => 977, 'name' => 'Teruel', 'state_id' => 41],
            ['id' => 978, 'name' => 'Tesalia', 'state_id' => 41],
            ['id' => 979, 'name' => 'Tibacuy', 'state_id' => 25],
            ['id' => 980, 'name' => 'Tibaná', 'state_id' => 15],
            ['id' => 981, 'name' => 'Tibasosa', 'state_id' => 15],
            ['id' => 982, 'name' => 'Tibirita', 'state_id' => 25],
            ['id' => 983, 'name' => 'Tibú', 'state_id' => 54],
            ['id' => 984, 'name' => 'Tierralta', 'state_id' => 23],
            ['id' => 985, 'name' => 'Timaná', 'state_id' => 41],
            ['id' => 986, 'name' => 'Timbiquí', 'state_id' => 19],
            ['id' => 987, 'name' => 'Timbío', 'state_id' => 19],
            ['id' => 988, 'name' => 'Tinjacá', 'state_id' => 15],
            ['id' => 989, 'name' => 'Tipacoque', 'state_id' => 15],
            ['id' => 990, 'name' => 'Tiquisio (Puerto Rico)', 'state_id' => 13],
            ['id' => 991, 'name' => 'Titiribí', 'state_id' => 5],
            ['id' => 992, 'name' => 'Toca', 'state_id' => 15],
            ['id' => 993, 'name' => 'Tocaima', 'state_id' => 25],
            ['id' => 994, 'name' => 'Tocancipá', 'state_id' => 25],
            ['id' => 995, 'name' => 'Toguí', 'state_id' => 15],
            ['id' => 996, 'name' => 'Toledo', 'state_id' => 5],
            ['id' => 997, 'name' => 'Toledo', 'state_id' => 54],
            ['id' => 998, 'name' => 'Tolú', 'state_id' => 70],
            ['id' => 999, 'name' => 'Tolú Viejo', 'state_id' => 70],
            ['id' => 1000, 'name' => 'Tona', 'state_id' => 68],
            ['id' => 1001, 'name' => 'Topagá', 'state_id' => 15],
            ['id' => 1002, 'name' => 'Topaipí', 'state_id' => 25],
            ['id' => 1003, 'name' => 'Toribío', 'state_id' => 19],
            ['id' => 1004, 'name' => 'Toro', 'state_id' => 76],
            ['id' => 1005, 'name' => 'Tota', 'state_id' => 15],
            ['id' => 1006, 'name' => 'Totoró', 'state_id' => 19],
            ['id' => 1007, 'name' => 'Trinidad', 'state_id' => 85],
            ['id' => 1008, 'name' => 'Trujillo', 'state_id' => 76],
            ['id' => 1009, 'name' => 'Tubará', 'state_id' => 8],
            ['id' => 1010, 'name' => 'Tuchín', 'state_id' => 23],
            ['id' => 1011, 'name' => 'Tulúa', 'state_id' => 76],
            ['id' => 1012, 'name' => 'Tumaco', 'state_id' => 52],
            ['id' => 1013, 'name' => 'Tunja', 'state_id' => 15],
            ['id' => 1014, 'name' => 'Tunungua', 'state_id' => 15],
            ['id' => 1015, 'name' => 'Turbaco', 'state_id' => 13],
            ['id' => 1016, 'name' => 'Turbaná', 'state_id' => 13],
            ['id' => 1017, 'name' => 'Turbo', 'state_id' => 5],
            ['id' => 1018, 'name' => 'Turmequé', 'state_id' => 15],
            ['id' => 1019, 'name' => 'Tuta', 'state_id' => 15],
            ['id' => 1020, 'name' => 'Tutasá', 'state_id' => 15],
            ['id' => 1021, 'name' => 'Támara', 'state_id' => 85],
            ['id' => 1022, 'name' => 'Támesis', 'state_id' => 5],
            ['id' => 1023, 'name' => 'Túquerres', 'state_id' => 52],
            ['id' => 1024, 'name' => 'Ubalá', 'state_id' => 25],
            ['id' => 1025, 'name' => 'Ubaque', 'state_id' => 25],
            ['id' => 1026, 'name' => 'Ubaté', 'state_id' => 25],
            ['id' => 1027, 'name' => 'Ulloa', 'state_id' => 76],
            ['id' => 1028, 'name' => 'Une', 'state_id' => 25],
            ['id' => 1029, 'name' => 'Unguía', 'state_id' => 27],
            ['id' => 1030, 'name' => 'Unión Panamericana (ÁNIMAS)', 'state_id' => 27],
            ['id' => 1031, 'name' => 'Uramita', 'state_id' => 5],
            ['id' => 1032, 'name' => 'Uribe', 'state_id' => 50],
            ['id' => 1033, 'name' => 'Uribia', 'state_id' => 44],
            ['id' => 1034, 'name' => 'Urrao', 'state_id' => 5],
            ['id' => 1035, 'name' => 'Urumita', 'state_id' => 44],
            ['id' => 1036, 'name' => 'Usiacuri', 'state_id' => 8],
            ['id' => 1037, 'name' => 'Valdivia', 'state_id' => 5],
            ['id' => 1038, 'name' => 'Valencia', 'state_id' => 23],
            ['id' => 1039, 'name' => 'Valle de San José', 'state_id' => 68],
            ['id' => 1040, 'name' => 'Valle de San Juan', 'state_id' => 73],
            ['id' => 1041, 'name' => 'Valle del Guamuez', 'state_id' => 86],
            ['id' => 1042, 'name' => 'Valledupar', 'state_id' => 20],
            ['id' => 1043, 'name' => 'Valparaiso', 'state_id' => 5],
            ['id' => 1044, 'name' => 'Valparaiso', 'state_id' => 18],
            ['id' => 1045, 'name' => 'Vegachí', 'state_id' => 5],
            ['id' => 1046, 'name' => 'Venadillo', 'state_id' => 73],
            ['id' => 1047, 'name' => 'Venecia', 'state_id' => 5],
            ['id' => 1048, 'name' => 'Venecia (Ospina Pérez)', 'state_id' => 25],
            ['id' => 1049, 'name' => 'Ventaquemada', 'state_id' => 15],
            ['id' => 1050, 'name' => 'Vergara', 'state_id' => 25],
            ['id' => 1051, 'name' => 'Versalles', 'state_id' => 76],
            ['id' => 1052, 'name' => 'Vetas', 'state_id' => 68],
            ['id' => 1053, 'name' => 'Viani', 'state_id' => 25],
            ['id' => 1054, 'name' => 'Vigía del Fuerte', 'state_id' => 5],
            ['id' => 1055, 'name' => 'Vijes', 'state_id' => 76],
            ['id' => 1056, 'name' => 'Villa Caro', 'state_id' => 54],
            ['id' => 1057, 'name' => 'Villa Rica', 'state_id' => 19],
            ['id' => 1058, 'name' => 'Villa de Leiva', 'state_id' => 15],
            ['id' => 1059, 'name' => 'Villa del Rosario', 'state_id' => 54],
            ['id' => 1060, 'name' => 'Villagarzón', 'state_id' => 86],
            ['id' => 1061, 'name' => 'Villagómez', 'state_id' => 25],
            ['id' => 1062, 'name' => 'Villahermosa', 'state_id' => 73],
            ['id' => 1063, 'name' => 'Villamaría', 'state_id' => 17],
            ['id' => 1064, 'name' => 'Villanueva', 'state_id' => 13],
            ['id' => 1065, 'name' => 'Villanueva', 'state_id' => 44],
            ['id' => 1066, 'name' => 'Villanueva', 'state_id' => 68],
            ['id' => 1067, 'name' => 'Villanueva', 'state_id' => 85],
            ['id' => 1068, 'name' => 'Villapinzón', 'state_id' => 25],
            ['id' => 1069, 'name' => 'Villarrica', 'state_id' => 73],
            ['id' => 1070, 'name' => 'Villavicencio', 'state_id' => 50],
            ['id' => 1071, 'name' => 'Villavieja', 'state_id' => 41],
            ['id' => 1072, 'name' => 'Villeta', 'state_id' => 25],
            ['id' => 1073, 'name' => 'Viotá', 'state_id' => 25],
            ['id' => 1074, 'name' => 'Viracachá', 'state_id' => 15],
            ['id' => 1075, 'name' => 'Vista Hermosa', 'state_id' => 50],
            ['id' => 1076, 'name' => 'Viterbo', 'state_id' => 17],
            ['id' => 1077, 'name' => 'Vélez', 'state_id' => 68],
            ['id' => 1078, 'name' => 'Yacopí', 'state_id' => 25],
            ['id' => 1079, 'name' => 'Yacuanquer', 'state_id' => 52],
            ['id' => 1080, 'name' => 'Yaguará', 'state_id' => 41],
            ['id' => 1081, 'name' => 'Yalí', 'state_id' => 5],
            ['id' => 1082, 'name' => 'Yarumal', 'state_id' => 5],
            ['id' => 1083, 'name' => 'Yolombó', 'state_id' => 5],
            ['id' => 1084, 'name' => 'Yondó (Casabe)', 'state_id' => 5],
            ['id' => 1085, 'name' => 'Yopal', 'state_id' => 85],
            ['id' => 1086, 'name' => 'Yotoco', 'state_id' => 76],
            ['id' => 1087, 'name' => 'Yumbo', 'state_id' => 76],
            ['id' => 1088, 'name' => 'Zambrano', 'state_id' => 13],
            ['id' => 1089, 'name' => 'Zapatoca', 'state_id' => 68],
            ['id' => 1090, 'name' => 'Zapayán (PUNTA DE PIEDRAS)', 'state_id' => 47],
            ['id' => 1091, 'name' => 'Zaragoza', 'state_id' => 5],
            ['id' => 1092, 'name' => 'Zarzal', 'state_id' => 76],
            ['id' => 1093, 'name' => 'Zetaquirá', 'state_id' => 15],
            ['id' => 1094, 'name' => 'Zipacón', 'state_id' => 25],
            ['id' => 1095, 'name' => 'Zipaquirá', 'state_id' => 25],
            ['id' => 1096, 'name' => 'Zona Bananera (PRADO - SEVILLA)', 'state_id' => 47],
            ['id' => 1097, 'name' => 'Ábrego', 'state_id' => 54],
            ['id' => 1098, 'name' => 'Íquira', 'state_id' => 41],
            ['id' => 1099, 'name' => 'Úmbita', 'state_id' => 15],
            ['id' => 1100, 'name' => 'Útica', 'state_id' => 25],
        ];

        foreach ($departments as $department) {
            DB::table('states')->upsert([
                [
                    'id' => $department['id'],
                    'name' => $department['name'],
                    'country_id' => 57,
                ],
            ], ['id']);
        }

        foreach ($cities as $city) {
            DB::table('cities')->upsert([
                [
                    'id' => $city['id'],
                    'name' => $city['name'],
                    'state_id' => $city['state_id'],
                ],
            ], ['id']);
        }
    }
}
